/**
 * Code Interpreter Output Types
 *
 * Defines strict TypeScript interfaces for code interpreter execution results
 * as returned by the OpenAI Responses API.
 *
 * @see https://platform.openai.com/docs/api-reference/responses/object
 */

/**
 * Complete Code Interpreter Call Output
 *
 * Top-level structure containing all information about code execution.
 * Returned in the response.code_interpreter_call field.
 */
export interface CodeInterpreterCallOutput {
  /**
   * Unique identifier for this code interpreter call
   *
   * Format: "call_" followed by alphanumeric string
   * Used to track execution across streaming events
   *
   * @example "call_abc123xyz789"
   */
  call_id: string;

  /**
   * Container ID where code was executed
   *
   * Format: "container_" followed by alphanumeric string
   * Can be reused across multiple API calls (1 hour session, 20min idle timeout)
   * Container costs $0.03 per creation
   *
   * @example "container_def456uvw012"
   */
  container_id: string;

  /**
   * Complete Python code that was executed
   *
   * Full code string as generated by the model
   * May contain multiple statements, imports, function definitions, etc.
   *
   * @example "import math\\nresult = math.factorial(5)\\nprint(result)"
   */
  code: string;

  /**
   * Array of execution outputs
   *
   * Contains logs (stdout/stderr), generated images, files, and errors
   * Multiple outputs can be produced by single code execution
   * Order matches execution sequence
   */
  output: CodeInterpreterOutput[];
}

/**
 * Code Interpreter Output Union Type
 *
 * Represents a single output item from code execution.
 * Can be logs, image, file, or error.
 */
export type CodeInterpreterOutput =
  | CodeInterpreterLogsOutput
  | CodeInterpreterImageOutput
  | CodeInterpreterFileOutput
  | CodeInterpreterErrorOutput;

/**
 * Code Interpreter Logs Output
 *
 * Captures stdout and stderr from Python code execution.
 */
export interface CodeInterpreterLogsOutput {
  /**
   * Output type discriminator
   */
  type: 'logs';

  /**
   * Combined stdout and stderr output
   *
   * Contains all print statements, warnings, and non-error messages
   * Captured during code execution
   *
   * @example "120\\nCalculation complete\\n"
   */
  logs: string;
}

/**
 * Code Interpreter Image Output
 *
 * Represents a generated image (plot, chart, visualization).
 */
export interface CodeInterpreterImageOutput {
  /**
   * Output type discriminator
   */
  type: 'image';

  /**
   * Image data or URL
   *
   * Can be:
   * - Base64 encoded image data (data:image/png;base64,...)
   * - Temporary URL to download image
   * - File ID for accessing via Files API
   *
   * Format depends on OpenAI API configuration and response format
   *
   * @example "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
   * @example "https://api.openai.com/v1/files/file-xyz123/content"
   */
  image: string;

  /**
   * Image filename (if available)
   *
   * Original filename generated by code interpreter
   *
   * @example "plot.png"
   */
  filename?: string;

  /**
   * File ID for accessing via Files API (if available)
   *
   * Format: "file-" followed by 24 alphanumeric characters
   *
   * @example "file-abc123xyz789012345678901"
   */
  file_id?: string;
}

/**
 * Code Interpreter File Output
 *
 * Represents a generated file (CSV, JSON, text, etc.).
 */
export interface CodeInterpreterFileOutput {
  /**
   * Output type discriminator
   */
  type: 'file';

  /**
   * File ID for accessing via Files API
   *
   * Format: "file-" followed by 24 alphanumeric characters
   * Use Files API GET /files/{file_id}/content to download
   *
   * @example "file-abc123xyz789012345678901"
   */
  file_id: string;

  /**
   * Filename as created by code
   *
   * Original filename generated during execution
   *
   * @example "results.csv"
   * @example "analysis_report.json"
   */
  filename: string;

  /**
   * File size in bytes (if available)
   */
  size?: number;

  /**
   * MIME type (if available)
   *
   * @example "text/csv"
   * @example "application/json"
   */
  mime_type?: string;
}

/**
 * Code Interpreter Error Output
 *
 * Represents an error that occurred during code execution.
 */
export interface CodeInterpreterErrorOutput {
  /**
   * Output type discriminator
   */
  type: 'error';

  /**
   * Error category
   *
   * - 'syntax': Python syntax error (code won't parse)
   * - 'runtime': Exception during execution (e.g., ZeroDivisionError)
   * - 'timeout': Execution exceeded time limit
   * - 'resource_limit': Memory or resource exhaustion
   * - 'unknown': Unclassified error
   */
  error_type: 'syntax' | 'runtime' | 'timeout' | 'resource_limit' | 'unknown';

  /**
   * Error message
   *
   * Detailed error description from Python interpreter
   * May include traceback information
   *
   * @example "ZeroDivisionError: division by zero"
   * @example "SyntaxError: invalid syntax (line 3)"
   */
  message: string;

  /**
   * Line number where error occurred (if available)
   *
   * For syntax and runtime errors that can be traced to specific line
   *
   * @example 3
   */
  line?: number;

  /**
   * Full traceback (if available)
   *
   * Complete Python traceback for debugging
   */
  traceback?: string;
}

/**
 * Code Interpreter Result Summary
 *
 * Simplified view of execution results for logging and display.
 * Useful for extracting key information without processing full output array.
 */
export interface CodeInterpreterResultSummary {
  /**
   * Whether code executed successfully without errors
   */
  success: boolean;

  /**
   * Container ID used for execution
   */
  container_id: string;

  /**
   * Total outputs produced
   */
  output_count: number;

  /**
   * Number of log outputs
   */
  logs_count: number;

  /**
   * Number of images generated
   */
  images_count: number;

  /**
   * Number of files generated
   */
  files_count: number;

  /**
   * Number of errors encountered
   */
  errors_count: number;

  /**
   * Array of generated file IDs
   */
  file_ids: string[];

  /**
   * Combined logs text
   */
  combined_logs: string;

  /**
   * First error message (if any)
   */
  first_error?: string;
}
